name: hms_web_app
description: A new Flutter project.

# Add this section to ensure compatibility
environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Add the http, url_launcher, and shared_preferences packages here
  http: ^0.13.5
  url_launcher: ^6.1.7
  shared_preferences: ^2.3.2

  # Add any other dependencies required by the project (if applicable)
  provider: ^6.0.5 # Optional: If using provider for state management

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/NWU_Logo.png  # Include your logo asset
